name: Run Python Script on Schedule

on:
  schedule:
    # Запуск каждый вторник в 22:10 по Московскому времени (пример cron: минуты часы день месяц день недели)
    - cron: '44 20 * * 2'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # или другая версия Python по вашему выбору
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run the script
      run: python raclub/testBot.py # Замените path/to/your/script.py на путь к вашему скрипту в репозитории
